on:
  workflow_run:
    workflows: ["blank.yml"]
    types: [completed]

jobs:
  hello:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ubuntu-latest]
    steps:
      - uses: hmarr/debug-action@v2
